<?= $this->extend('Layouts/coreLayout'); ?>
<?= $this->section('content'); ?>
<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <!-- <h1 class="m-0 text-dark"></h1> -->
            </div><!-- /.col -->
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="<?= base_url() ?>/dashboard">Dashboard</a></li>
                    <li class="breadcrumb-item active"><?= $page['heading'] ?></li>
                </ol>
            </div><!-- /.col -->
        </div><!-- /.row -->
    </div><!-- /.container-fluid -->
</div>

<div class="container-fluid">
    <div class="card">
        <div class="card-header"></div>
        <div class="card-body" id="billRests">
            <table id="example1" class="table table-sm table-bordered ">
                <thead>
                    <tr>
                        <th>Payer Name</th>
                        <th>Control Number</th>
                        <th>Billed Amount</th>
                        <th>Generated On</th>
                        <th>Generated By</th>
                        <th>Requested By</th>
                        <th>Reason</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    <?php
                    function cleanStr($str): string
                    {
                        return preg_replace('/[^a-zA-Z0-9\s]/', ' ', $str);
                    }
                    ?>
                    <?php foreach ($bills as $bill) : ?>
                        <?php
                        $type = '';


                        ?>

                        <tr class="<?= 'bill'.$bill->RequestId ?>">
                            <td><?= $bill->PyrName ?></td>
                            <td><?= $bill->PayCntrNum ?></td>
                            <td><?= number_format($bill->BillAmt) ?>(TZS)</td>
                            <td><?= dateFormatter($bill->BillGenDt) ?></td>
                            <td><?= $bill->BillGenBy ?></td>
                            <td><?= $bill->requestedBy ?></td>
                            <td><?= $bill->reason ?></td>
                            <?php if(!$user->inGroup('officer')): ?>
                                <td>
                                <?php if ($bill->isTrBill == 'Yes'): ?>
                                    <button type="button" class="btn btn-primary btn-xs" onclick="approveBillCancellation(`<?= $bill->RequestId ?>`,`<?= cleanStr($bill->reason) ?>`,`<?= cleanStr($bill->requestedBy) ?>`,`<?= $type ?>`)"><i class="fas fa-check"></i> TR Bill Approve</button>

                                <?php else: ?>
                                    <button type="button" class="btn btn-primary btn-xs" onclick="approveCancellation(`<?= $bill->billId ?>`,`<?= cleanStr($bill->reason) ?>`,`<?= cleanStr($bill->requestedBy) ?>`)"><i class="fas fa-check"></i>Normal Bill Approve</button>

                                <?php endif; ?>

                            </td>
                            <?php else: ?>
                                <td></td>
                            <?php endif; ?>
                            
                        </tr>

                    <?php endforeach; ?>

                </tbody>
            </table>
        </div>
    </div>

    <script>
        // function approveCancellation(billId, reason) {
        //     console.log(billId, reason)
        // }

        function approveBillCancellation(requestId, reason, requestedBy, type) {




            swal({
                    title: "Are You Sure You Want To Cancel The Bill?",
                    // text: "Once deleted, you will not be able to recover this imaginary file!",
                    icon: "warning",
                    buttons: true,
                    buttons: ["No", "Yes"],
                    dangerMode: true,
                })
                .then((willCancel) => {

                    if (willCancel) {

                        fetch('billCancellationApproval', {
                                method: 'POST',
                                headers: {
                                    'Content-Type': 'application/json;charset=utf-8',
                                    "X-Requested-With": "XMLHttpRequest",
                                    'X-CSRF-TOKEN': document.querySelector('.token').value
                                },

                                body: JSON.stringify({
                                    requestId: requestId,
                                    reason: reason,
                                    requestedBy: requestedBy,
                                }),

                            }).then(response => response.json())
                            .then(data => {
                                const {
                                    requestId,
                                    token,
                                    status,
                                    msg,
                                    code

                                } = data
                                document.querySelector('.token').value = token
                                if (status == 1) {
                                    console.log(requestId)
                                    // document.querySelector('#billRests').innerHTML = bills
                                    document.querySelector(`.bill${requestId}`).remove()
                                    swal({
                                        title: msg,
                                        icon: "success",
                                        // timer: 5500
                                    });
                                } else {
                                    swal({
                                        title: msg,
                                        text: code,
                                        icon: "warning",
                                        // timer: 18500
                                    });
                                }
                                console.log(data)
                            })

                    } else {
                        swal("Bill Is Not Cancelled ");
                    }
                });



        }

        //this is for non combined bills
        function approveCancellation(billId, reason, requestedBy) {




            swal({
                    title: "Are You Sure You Want To Cancel The Bill?",
                    // text: "Once deleted, you will not be able to recover this imaginary file!",
                    icon: "warning",
                    buttons: true,
                    buttons: ["No", "Yes"],
                    dangerMode: true,
                })
                .then((willCancel) => {

                    if (willCancel) {

                        fetch('wmaBillCancellationApproval', {
                                method: 'POST',
                                headers: {
                                    'Content-Type': 'application/json;charset=utf-8',
                                    "X-Requested-With": "XMLHttpRequest",
                                    'X-CSRF-TOKEN': document.querySelector('.token').value
                                },

                                body: JSON.stringify({
                                    billId: billId,
                                    reason: reason,
                                    requestedBy: requestedBy,
                                }),

                            }).then(response => response.json())
                            .then(data => {
                                const {
                                    billId,
                                    token,
                                    status,
                                    msg,
                                    code

                                } = data
                                document.querySelector('.token').value = token
                                if (status == 1) {

                                    // document.querySelector('#billRests').innerHTML = bills
                                    document.querySelector(`.bill${billId}`).remove()
                                    swal({
                                        title: msg,
                                        icon: "success",
                                        // timer: 5500
                                    });
                                } else {
                                    swal({
                                        title: msg,
                                        text: code,
                                        icon: "warning",
                                        // timer: 18500
                                    });
                                }
                                console.log(data)
                            })

                    } else {
                        swal("Bill Is Not Cancelled ");
                    }
                });



        }
    </script>




    <?= $this->endSection(); ?>