<?= $this->extend('Layouts/coreLayout'); ?>
<?= $this->section('content'); ?>
<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <!-- <h1 class="m-0 text-dark"></h1> -->
            </div><!-- /.col -->
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="<?= base_url() ?>/dashboard">Dashboard</a></li>
                    <li class="breadcrumb-item active"><?= $page['heading'] ?></li>
                </ol>
            </div><!-- /.col -->
        </div><!-- /.row -->
    </div><!-- /.container-fluid -->
</div>

<div class="container-fluid">
    <div class="card">
        <div class="card-header"></div>
        <div class="card-body">
            <table id="example1" class="table table-sm table-bordered">
                <thead>
                    <tr>
                        <th>Region</th>
                        <th>Payer Name</th>
                        <th>Control Number</th>
                        <th>Billed Amount</th>
                        <th>Generated On</th>
                        <th>Generated By</th>
                        <th>Cancelled On</th>
                        <th>Cancelled By</th>
                        <th>Approved  By</th>
                        <th>Reason</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($bills as $bill) : ?>
                        <tr>
                            <td><?= str_replace('Wakala Wa Vipimo', ' ', wmaCenter($bill->CollectionCenter)->centerName) ?></td>
                            <td><?= $bill->PyrName ?></td>
                            <td><?= $bill->PayCntrNum ?></td>
                            <td><?= number_format($bill->BillAmt) ?>(TZS)</td>
                            <td><?= dateFormatter($bill->BillGenDt)?></td>
                            <td><?= $bill->BillGenBy ?></td>
                            <td><?= dateFormatter($bill->CancelDate)?></td>
                            <td><?= $bill->CanceledBy ?></td>
                            <td><?= $bill->ApprovedBy ?></td>
                            <td><?= $bill->CanclReasn ?></td>
                        </tr>

                    <?php endforeach; ?>

                </tbody>
            </table>
        </div>
    </div>

    <script>
    $(document).ready(function() {
        $('#billTable').DataTable({
            dom: '<"top"lBfrtip>',
            buttons: [
                'csv', 'excel', 'pdf' ,'print'
            ],
            lengthMenu: [10, 25, 34, 50, 100]
        });
    });
</script>




    <?= $this->endSection(); ?>